### PR TITLE
Squash merge feature/DLOB-1750-nexttrainnumber-fixes

### PR DESCRIPTION
**Pull request by blackus3r**
## Fixes
Removed 'train' from nextTrainNumber and nextTrainLinkType because it is redundant and added nextPiNumber.

### CODE REVIEW

**Review by Shyru — COMMENTED** [review]
Ahem, excuse me!? 😳
This is a backwards incompatible change!?
You cannot simply rename a field that is used in more than twenty trains all over the world simply with a minor .1 point-release!!? What is you upgrade strategy for Motion? What is you update-strategy for OnBoard?
Also LiNetCo has already implemented support for continuations based on the Spec in version 2.4.0!
So whats your plan with this? 🤔

**Comment by blackus3r** [comment]
The schema was not correct, the implementation in motion and onboard was another one. 


I will ask LiNetCo

**Comment by blackus3r** [comment]
As we have discussed: 
This is the current living standard. We have to fix all occurrences in onboard (backend)

@skullbooks Daniel said, you can merge this, after you have reviewed it.

**Review by skullbooks — APPROVED** [review]
Good!

**Pull request merged**
